kind: Template
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    labels:
      app: kubernetes-image-puller
    name: kubernetes-image-puller
  spec:
    replicas: ${{REPLICAS}}
    revisionHistoryLimit: 2
    selector:
      app: kubernetes-image-puller
    strategy:
      type: "Recreate"
    template:
      metadata:
        labels:
          app: kubernetes-image-puller
      spec:
        containers:
        - name: kubernetes-image-puller
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - /kubernetes-image-puller
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - pgrep
                - -f
                - /kubernetes-image-puller
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 5m
              memory: 5Mi
            limits:
              cpu: 100m
              memory: 50Mi
          envFrom:
          - configMapRef:
              name: kubernetes-image-puller
          env:
          - name: SERVICE_ACCOUNT_ID
            valueFrom:
              secretKeyRef:
                name: ${SERVICE_ACCT_CREDENTIALS_SECRET}
                key: service.account.id
          - name: SERVICE_ACCOUNT_SECRET
            valueFrom:
              secretKeyRef:
                name: ${SERVICE_ACCT_CREDENTIALS_SECRET}
                key: service.account.secret
        serviceAccountName: ${SERVICEACCOUNT_NAME}
parameters:
- name: SERVICEACCOUNT_NAME
  value: rhche
- name: SERVICE_ACCT_CREDENTIALS_SECRET
  value: rhche
- name: IMAGE
  value: quay.io/openshiftio/rhel-kubernetes-image-puller
- name: IMAGE_TAG
  value: latest
- name: REPLICAS
  value: "3"
